import {
  Bus,
  CircleEllipsis,
  Coffee,
  Fuel,
  Gift,
  GraduationCap,
  HeartPulse,
  KeyRound,
  Landmark,
  Plane,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Ticket,
  Tv,
  Utensils,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-preact';
import type { CategoryKey } from '../../shared/categories';

/** Lucide icon per category — the same names as CATEGORIES[k].icon in src/shared/categories.ts. */
export const CATEGORY_ICON: Record<CategoryKey, LucideIcon> = {
  courses: ShoppingCart,
  loyer: KeyRound,
  factures: Zap,
  transport: Bus,
  essence: Fuel,
  sante: HeartPulse,
  maison: Wrench,
  ecole: GraduationCap,
  credit: Landmark,
  resto: Utensils,
  cafe: Coffee,
  shopping: ShoppingBag,
  vetements: Shirt,
  sortie: Ticket,
  voyage: Plane,
  abonnement: Tv,
  cadeau: Gift,
  beaute: Scissors,
  autre: CircleEllipsis,
};
