/* Bundles the notify-run core (src/server/notify + src/shared, fr.json inlined)
 * into one ESM file the Deno Edge Function imports. supabase-js and web-push
 * are not bundled: the function imports them itself (npm: specifiers).
 * Fails if the bundle would need a Node built-in the edge runtime lacks. */
import { build } from 'esbuild';
import { readFileSync } from 'node:fs';

const outfile = 'supabase/functions/notify-run/core.js';

await build({
  entryPoints: ['src/server/notify/edge.ts'],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  mainFields: ['module', 'main'],
  outfile,
  legalComments: 'none',
  banner: { js: '/* Generated by scripts/build-notify.mjs — do not edit. */' },
  logLevel: 'warning',
});

const code = readFileSync(outfile, 'utf8');
const bad = code.match(/\bfrom\s+["']node:[^"']+["']|\brequire\(\s*["'][^"']+["']\s*\)|\bimport\(\s*["']node:/g);
if (bad) {
  console.error(`build-notify: ${outfile} still imports ${[...new Set(bad)].join(', ')}`);
  process.exit(1);
}
/* 78 kB without zod; 824 kB the day aam/load's schemas leaked in (Phase 6 M11) */
const MAX_KB = 200;
const kb = code.length / 1024;
if (kb > MAX_KB) {
  console.error(`build-notify: ${outfile} is ${kb.toFixed(1)} kB, over ${MAX_KB} kB — something heavy got bundled`);
  process.exit(1);
}
console.log(`build-notify: ${outfile} (${kb.toFixed(1)} kB)`);
